- name: "Deploy with Ansible"
  hosts: localhost
  gather_facts: true
  vars:
    # general
    ansible_group: nic
    ansible_user: nic
    backup_server: true
    primary_server: false
    do_syncoid: true
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/ssh-setup.yml
    - import_tasks: tasks/cargo.yml
    # - import_tasks: tasks/stow.yml
    # - import_tasks: tasks/zsh-setup.yml
    # - import_tasks: tasks/nvim-setup.yml
  roles:
    - role: zfs-and-sanoid
      become: true
      tags:
        - zfs
