- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False
  vars:
    user: "{{ ansible_user_id }}"

  roles:
    # - role: geerlingguy.ruby
    #   tags:
    #     - core
    #     - ruby
    - role: suzuki-shunsuke.pyenv-module
      tags:
        - core
        - pyenv
    # - role: markosamuli.pyenv
    #   tags:
    #     - core
    #     - pyenv

  tasks:
    - include: tasks/core.yml
    - include: tasks/repos.yml
    - include: tasks/stow.yml
    - include: tasks/desktop.yml
    - include: tasks/node-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/zsh-setup.yml

