---
- name: Configure all machines
  hosts: all
  gather_facts: true

  roles:
    - role: homebrew
      tags: ['brew']
    
    - role: neovim
      tags: ['neovim']
    
    - role: base-system
      tags: ['base']
    
    - role: git-setup
      tags: ['git']
    
    - role: shell-setup
      tags: ['shell']
      when: setup_shell | default(true)
    
    - role: development
      tags: ['dev']
      when: install_development_tools | default(false)
    
    - role: geerlingguy.docker
      tags: ['docker', 'dev']
      when: install_docker | default(false)
      become: true

    - role: docker
      tags: ['docker', 'dev']
      when: install_docker | default(false)
