- name: Ensure brew path 
  shell: export PATH={{  lookup('env', 'HOME') }}/.linuxbrew/bin:$PATH

- name: Brew Install tmux
  community.general.homebrew:
    name: tmux
    state: present

- name: fzf
  community.general.homebrew:
    name: fzf
    state: present

- name: glow
  community.general.homebrew:
    name: glow
    state: present

- name: gitui
  community.general.homebrew:
    name: gitui
    state: present

