- name: Remove neovim
  shell: rm -rf "{{ lookup('env', 'HOME')  }}/third-party/neovim"
  become: true
  tags:
    - install
    - install-nvim 
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/third-party/neovim"
    version: nightly
  ignore_errors: yes
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - install-nvim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/third-party/neovim && make -j 20"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/third-party/neovim && make install"
  tags:
    - install
    - neovim

- name: Check if python3 nvim env exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/dotfiles/.venv/nvim/"
  register: pynvim_venv3_exists
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim

- name: Create python3 nvim environment 
  when: pynvim_venv3_path.stat.islnk is not defined
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  shell: |
    cd {{ lookup('env', 'HOME') }}/dotfiles
    python3 -m venv .venv/nvim

- name: Install pynvim into venv3
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
  shell: "{{ lookup('env', 'HOME') }}/dotfiles/.venv/nvim/bin/pip install pynvim"

- name: Install pyflyby 
  shell: "{{ global_pipx_alias }} install pyflyby --force "
  tags:
    - install
    - python
    - dotfiles
    - nvim
