- name: Install copier
  community.general.pipx:
    name: copier
    executable: 
  tags:
    - copier
    - install

- name: Install Python LSP Server
  community.general.pipx:
    name: 'python-lsp-server[all]'

- name: Install MyPy in Python LSP
  shell: pipx inject python-lsp-server pylsp-mypy

- name: Install Jedi LSP
  community.general.pipx:
    name: jedi-language-server

- name: Install Black
  community.general.pipx:
    name: black

- name: Install Isort
  community.general.pipx:
    name: isort

- name: Install flake8
  community.general.pipx:
    name: flake8

- name: Install doq
  community.general.pipx:
    name: doq
