- name: Install pipx
  ansible.builtin.pip:
    executable: "{{ global_pip_alias }}"  # requires pyenv role to run successfully
    extra_args: --isolated
    name: pipx


- name: Install copier
  community.general.pipx:
    name: copier
    executable: "{{ global_pipx_alias }}"
  tags:
    - copier
    - install

- name: Install Python LSP Server
  community.general.pipx:
    name: 'python-lsp-server[all]'
    executable: "{{ global_pipx_alias }}"

- name: Install MyPy in Python LSP
  shell: "{{ global_pipx_alias }} inject python-lsp-server pylsp-mypy"

- name: Install Jedi LSP
  community.general.pipx:
    name: jedi-language-server
    executable: "{{ global_pipx_alias }}"

- name: Install Black
  community.general.pipx:
    name: black
    executable: "{{ global_pipx_alias }}"

- name: Install Isort
  community.general.pipx:
    name: isort
    executable: "{{ global_pipx_alias }}"

- name: Install flake8
  community.general.pipx:
    name: flake8
    executable: "{{ global_pipx_alias }}"

- name: Install doq
  community.general.pipx:
    name: doq
    executable: "{{ global_pipx_alias }}"
