- name: ensure personal git directory
  file:
    path: "{{ lookup('env', 'HOME') }}/personal"
    state: directory
  tags:
    - repos

- name: ensure work directory
  file:
    path: "{{ lookup('env', 'HOME') }}/work"
    state: directory
  tags:
    - repos

- name: ensure third-party directory
  file:
    path: "{{ lookup('env', 'HOME') }}/third-party"
    state: directory
  tags:
    - repos

- name: Clone Blog
  ansible.builtin.git:
    repo: 'https://github.com/pypeaday/pype.dev.git'
    dest: "{{ lookup('env', 'HOME') }}/personal/pype.dev"
    update: no

- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/pypeaday/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    update: no
  ignore_errors: yes
  tags:
    - install

- name: Clone Nord Rofi Theme
  ansible.builtin.git:
    repo: 'https://github.com/undiabler/nord-rofi-theme.git'
    dest: "{{ lookup('env', 'HOME') }}/third-party/nord-rofi-theme"
    update: no

- name: Clone fancy-motd 
  ansible.builtin.git:
    repo: 'https://github.com/pypeaday/fancy-motd.git'
    dest: "{{ lookup('env', 'HOME') }}/personal/fancy-motd"
    update: no
  tags:
    - motd

