---
- name: Install Prerequisite software
  apt:
    pkg:
      - debhelper
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - pv
      - lzop
      - mbuffer
      - build-essential
  tags:
    - sanoid
  ignore_errors: yes

- name: git clone
  ansible.builtin.shell: sudo git clone https://github.com/jimsalterjrs/sanoid.git
  become: yes
  ignore_errors: yes

- name: Checkout relevant latest stable release
  become: yes
  ansible.builtin.shell: |
    cd sanoid 
    git checkout $(git tag | grep "^v" | tail -n 1)
    # checkout latest stable release or stay on master for bleeding edge stuff (but expect bugs!)
    git checkout $(git tag | grep "^v" | tail -n 1)
    # Install the executables
    sudo cp sanoid syncoid findoid sleepymutex /usr/local/sbin
    # Create the config directory
    sudo mkdir /etc/sanoid
    # Install default config
    sudo cp sanoid.defaults.conf /etc/sanoid
    # Create a blank config file
    # sudo touch /etc/sanoid/sanoid.conf
    # Place the sample config in the conf directory for reference
    sudo cp sanoid.conf /etc/sanoid/sanoid.example.conf

- name: Enable timer
  become: yes
  ansible.builtin.shell: |
    # enable and start the sanoid timer
    sudo systemctl enable sanoid.timer
    sudo systemctl start sanoid.timer
