---
- name: Create user group
  group:
    name: "{{ ansible_group }}"
    state: present

- name: Create user
  user:
    name: "{{ ansible_user }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: "{{ ansible_group }}"

