---
- name: Install ZFS
  apt:
    name:
      - zfs-dkms
      - zfsutils-linux
  tags:
    - zfs

- name: Install Prerequisites for Sanoid
  apt:
    pkg:
      - debhelper
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - pv
      - lzop
      - mbuffer
      - build-essential
  tags:
    - sanoid
    - zfs
  ignore_errors: yes

- name: Clone Sanoid
  become: yes  # Jim recommends all sanoid stuff just happen as root
  ansible.builtin.git:
    repo: 'https://github.com/jimsalterjrs/sanoid.git'
    dest: "{{ lookup('env', 'HOME') }}/sanoid"
    update: no
  tags:
    - sanoid
    - zfs

- name: Checkout relevant latest stable release
  become: yes
  ansible.builtin.shell: |
    cd {{ lookup('env', 'HOME') }}/sanoid
    # checkout latest stable release or stay on master for bleeding edge stuff (but expect bugs!)
    git checkout $(git tag | grep "^v" | tail -n 1)
    ln -s packages/debian .
    dpkg-buildpackage -uc -us
    apt install ../sanoid_*_all.deb
  tags:
    - sanoid
    - zfs

- name: Enable timer
  become: yes
  ansible.builtin.shell: |
    # enable and start the sanoid timer
    sudo systemctl enable sanoid.timer
    sudo systemctl start sanoid.timer
  tags:
    - sanoid
    - zfs

- name: Copy sanoid.conf from dotfiles to /etc/sanoid
  become: yes
  ansible.builtin.shell: sudo wget https://raw.githubusercontent.com/pypeaday/dotfiles/main/sanoid.conf /etc/sanoid/sanoid.conf
  tags:
    - sanoid
    - zfs
