- name: check is zsh installed
  shell: command -v zsh
  register: zsh_exists
  ignore_errors: yes
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Install ZSH
  when: zsh_exists is failed
  become: true
  apt: name=zsh
  tags: *tags_for_zsh_tasks

- name: Check if oh-my-zsh is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: ohmyzsh_path
  tags: *tags_for_zsh_tasks

# - name: Check if oh-my-zsh is installed at root
#   stat:
#     path: "/root/.oh-my-zsh"
#   register: ohmyzsh_root_path
#   tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
  # when: ohmyzsh_path.stat.islnk is not defined and ohmyzsh_root_path.stat.islnk is not defined
  when: ohmyzsh_path.stat.islnk is not defined
  tags: *tags_for_zsh_tasks
  become_user: "{{ ansible_user }}" 

- name: Check if zsh-autosuggestions is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  register: zshautosuggestions_path
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  when: zshautosuggestions_path.stat.islnk is not defined
  tags: *tags_for_zsh_tasks
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: Check if zsh-history-substring-search is installed
  tags: *tags_for_zsh_tasks
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-history-substring-search"
  register: zsh_history_substring_search_path

- name: Install zsh-history-substring-search
  tags: *tags_for_zsh_tasks
  when: zsh_history_substring_search_path.stat.islnk is not defined
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-history-substring-search.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-history-substring-search"

- name: check is starship installed
  shell: command -v starship
  register: starship_exists
  ignore_errors: yes
  tags: *tags_for_zsh_tasks

- name: Install Starship
  when: starship_exists is failed
  become: true
  tags: *tags_for_zsh_tasks
  shell: |
    curl -fsSL https://starship.rs/install.sh | sh -s -- -y
    # cat ~/.bashrc | grep -q 'eval "$(starship init bash)"' || echo 'eval "$(starship init bash)"' >> ~/.bashrc
    # cat ~/.zshrc | grep -q 'eval "$(starship init zsh)"' || echo 'eval "$(starship init zsh)"' >> ~/.zshrc
# - name: Check if forgit is installed
#   stat:
#     path: "{{ lookup('env', 'HOME') }}/.forgit"
#   register: forgit_exists
#   tags: *tags_for_zsh_tasks

