---
- name: Get the user shell
  ansible.builtin.shell: |
    getent passwd {{ ansible_user_id }} | cut -d: -f7 | rev | cut -d/ -f1 | rev
  args:
    executable: /bin/bash
  changed_when: false
  register: user_shell

- name: Add homebrew path to system-wide $PATH for bash shell (Debian OS Family).
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user_id }}/.profile"
    line: "PATH=$PATH:~/.linuxbrew/bin"
    owner: "{{ ansible_user_id }}"
    mode: 0644
    create: yes
  when: 
    - user_shell.stdout == "bash" and ansible_os_family == "Debian"

- name: Add homebrew path to system-wide $PATH for bash shell (RedHat OS Family).
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user_id }}/.bash_profile"
    line: "PATH=$PATH:~/.linuxbrew/bin"
    owner: "{{ ansible_user_id }}"
    mode: 0644
    create: yes
  when: 
    - user_shell.stdout == "bash" and ansible_os_family == "RedHat"

- name: Add homebrew path to system-wide $PATH for fish shell.
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user_id }}/.config/fish/conf.d/brew.fish"
    content: "set -gx PATH $PATH /home/{{ ansible_user_id }}/.linuxbrew/bin"
    owner: "{{ ansible_user_id }}"
    mode: 0644
  when: user_shell.stdout == "fish"

- name: Add homebrew path to system-wide $PATH for zsh shell.
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user_id }}/.zprofile"
    line: "PATH=$PATH:~/.linuxbrew/bin"
    owner: "{{ ansible_user_id }}"
    mode: 0644
    create: yes
  when: user_shell.stdout == "zsh"
