---
- name: Install kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  become: true

- name: Install Helm with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/helm/helm! | bash
  become: true

- name: Install k9s with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/derailed/k9s! | bash
  become: true

- name: Install kubecm with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/sunny0826/kubecm! | bash
  become: true
