---
- name: Install Node.js and npm
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_lts.x
    dest: /tmp/ansible-playbooks-setup/setup_node.sh
  register: node_download
  become: true

- name: Run Node.js setup script
  ansible.builtin.shell: |
    bash /tmp/ansible-playbooks-setup/setup_node.sh | sudo -E bash -
    apt-get install -y nodejs
  args:
    executable: /bin/bash
    creates: /usr/bin/node
  when: node_download.changed
  become: true

- name: Install Rust
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/ansible-playbooks-setup/rustup.sh
  register: rust_download
  become: true

- name: Run Rust setup script
  ansible.builtin.shell: |
    sh /tmp/ansible-playbooks-setup/rustup.sh -y
  args:
    creates: "{{ home_dir }}/.cargo/bin/rustc"
    executable: /bin/bash
  become: false
  when: rust_download.changed

- name: Install Zellij with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/zellij-org/zellij! | bash
  become: true

- name: Install direnv with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/direnv/direnv! | bash
  become: true

- name: Install tree-sitter with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/tree-sitter/tree-sitter! | bash
  become: true

- include_tasks: kubernetes.yml
  tags:
    - kubernetes
    - k8s

- include_tasks: terraform.yml
  tags:
    - terraform
    - infra

- name: Install Bitwarden Secrets Manager CLI with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/bitwarden/sdk-sm! | bash
  become: true

- name: Install skm SSH key manager with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/TimothyYe/skm! | bash
  become: true

- name: Install fly cli
  ansible.builtin.shell: curl -L https://fly.io/install.sh | sh

