---
- name: Install Zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Change default shell to Zsh
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
  become: true

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ home_dir }}/.oh-my-zsh"
  become: false

- name: Install Zsh plugins
  ansible.builtin.git:
    repo: "https://github.com/{{ item }}.git"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/{{ item | split('/') | last }}"
    depth: 1
  with_items:
    - zsh-users/zsh-autosuggestions
    - zsh-users/zsh-syntax-highlighting
  become: false
