# Main playbook for my dev tools. Since switching to Aurora I really don't want to manage so much stuff
---
- name: Setup Devtools
  hosts: localhost
  become: false

  vars:
    brew_packages:
      - git
      - gitui
      - helm
      - kubectl
      - neovim
      - python
      - stow
      - vim
      - ripgrep
      - dust
      - ijq
      - jq

    flatpak_packages:
      - com.spotify.Client
      - flathub org.signal.Signal

  tasks:

  - name: Change shell to Zsh if not already
    shell: chsh -s $(which zsh) {{ ansible_user_id }}
    when: shell != "/bin/zsh"

  - name: Oh-My-Zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

  - name: Check if Homebrew exists
    shell: command -v brew
    register: brew_exists
    ignore_errors: yes
    # TODO: stuff



  - name: Install Homebrew
    shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    when: brew_exists is failed

  - name: Install Homebrew packages
    homebrew:
      name: "{{ brew_packages }}"
      state: present

  - name: Install Flatpak packages
    flatpak:
      name: "{{ flatpak_packages }}"
      state: present