---
- name: Download neovim tarball from GitHub releases
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"
    mode: '0644'
  become: true

- name: Extract neovim to /usr/local
  ansible.builtin.unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "/usr/local"
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: true

- name: Clean up neovim tarball
  ansible.builtin.file:
    path: "/tmp/nvim-linux64.tar.gz"
    state: absent
  become: true
