---
- name: Configure git global settings
  ansible.builtin.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: 'core.editor', value: 'vim' }
    - { name: 'init.defaultBranch', value: 'main' }
    - { name: 'credential.helper', value: 'store' }
  become: false

- name: Create SSH directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh"
    state: directory
    mode: '0700'
  become: false

- name: Check for existing SSH key
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh/id_{{ ansible_facts['hostname'] }}"
  register: ssh_key
  become: false

- name: Generate SSH key pair
  community.crypto.openssh_keypair:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh/id_{{ ansible_facts['hostname'] }}"
    type: ed25519
    comment: "{{ ansible_facts['user_id'] }}@{{ ansible_facts['hostname'] }}"
  when: not ssh_key.stat.exists
  become: false

- name: Install lazygit with installer
  ansible.builtin.shell: |
    curl -L i.paynepride.com/jesseduffield/lazygit! | bash
  become: true

